name: Dotnet Desktop

on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        default: 'auto'

  push:
    tags: ['v*']     # 推 tag 時會帶入版號

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Resolve version
        id: ver
        shell: pwsh
        run: |
          if ("${{ github.ref }}" -like "refs/tags/v*") {
            $v = "${{ github.ref }}".Replace("refs/tags/v","")
          } elseif ("${{ inputs.version }}" -ne "") {
            $v = "${{ inputs.version }}"
          } else {
            $short = "${{ github.sha }}".Substring(0,7)
            $v = "0.0.0+run.${{ github.run_number }}-$short"
          }
          "VERSION=$v" | Out-File -FilePath $env:GITHUB_ENV -Append
          Write-Host "VERSION=$v"

      - name: Run shared CI script
        shell: pwsh
        run: pwsh -File scripts/desktop-ci.ps1 -Version "${{ env.VERSION }}" -DoRelease

      - uses: actions/upload-artifact@v4
        with:
          name: build-${{ env.VERSION }}
          path: |
            installer/artifacts/**/*
            installer/artifacts/output/*

  release:
    needs: build
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: windows-latest
    steps:
      - uses: actions/download-artifact@v4
        with: { path: dist }
      - uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          files: |
            dist/**/*.zip
            dist/**/Markdown2Doc-Setup-*.exe
